Algoritmo "celsius2fahrenheit"
// 
//  
// Descrição   : Ler uma temperatura em graus Celsius e apresentá-la convertida em graus Fahrenheit
// Autor(a)    : Rafael Lima
// Data atual  : 25/07/2020
Var
  C, F: real


Inicio
  escreval ("Informe a temperatura em graus celsius ")
  leia (C)
  F <- (9*C+160)/5
  escreval ("A temperatura convertida de Celsius para Fahrenheit é ", F)


Fimalgoritmo